// Suite: Replay.test - replay integration test (task A11): the recorded Demo walk track drives the real pipeline.
// Owner: task A11 (Person A). Registered in List.test.ets by T1 (do not rename the exported function).
//
// Fixture: fixtures/DemoTrackMini.ets (SIMULATED, generated by `node scripts/demo/make-demo-walk.mjs --fixture`):
// the last five stops of the Royal Route demo walk (7 St Adalbert's, 8 Sts Peter and Paul, 9 St Andrew's,
// 10 Kanonicza, 11 Wawel). The demo walk is PLAIN (predictable for a live demo): the stops in the planner's order with
// a 40 s dwell (hold segment) at every stop; its one scripted moment is the ~80 m detour off Grodzka between stops 7
// and 8 (off-route -> re-plan, which keeps stop 8 next).
//
// Layer 1 (pure core, deterministic, no timers): Planner (Held-Karp) -> DemoWalkPlayer (hold while a story plays,
// like DemoWalkSource) -> TourEngine (which runs FixFilter on every fix) with a fake clock and a fake speech engine
// that needs 2.5 s per sentence. An independent FixFilter classifies the same fixes as a probe.
// Runs: voice x1 (track time), voice x4 and x8 (wall-clock stamps, as on the emulator), text-only x1 (TICK pacing).
// Layer 2: the same track through the real TourController (fake ports: manual clock + scheduler, pack, speech,
// a demo source that wraps DemoWalkPlayer exactly like DemoWalkSource) at x8, the DevPanel "Start demo tour" flow;
// and at x2 (the Home card's demo speed) with Skip pressed at every stop: the walker jumps to the tour's new target.
//
// Jury-relevant outcomes asserted: every planned stop entered exactly once and in the planned order, and at no
// moment is a later stop visited while an earlier one is still open; the full story at every stop, at x1 (real
// walking pace) as well as x8; no story cut mid-sentence (no STOP_SPEECH, no overlapping sentence, every item
// completes, a stop's story is never interleaved with another); finished state; no arrival during the detour; every
// fix of the plain walk is trigger-grade.
// A9 (turn-by-turn, off-route): the fixture carries the pack's legs between the fixture stops (routes.json, the track
// walks them), so the engine tracks every leg: spoken turn cues fire on the walk (NAV_CUE kind=now, each cue once);
// the ~80 m detour gives exactly one OFF_ROUTE inside its window (also at x4/x8 with wall-clock stamps), then
// REQUEST_REPLAN -> Planner from the current fix -> PLAN_READY (REPLAN changed=0) and ON_ROUTE once the walker is
// back; nowhere else on the normal track is the walker off the route (no false positive).
// Each run prints one `REPLAY_SUMMARY ...` line (pasted into the README "Testing" section and the A11 PR).
import { describe, it, expect } from 'vitest';
import { StepResult, TourEngine, TourInput, TourState } from '../src';
import { TourConfig } from '../src';
import { FilteredFix, FixFilter } from '../src';
import { CityPack, PlanInputs, buildCostInputs, plan as planRoute } from '../src';
import { DemoFix, DemoTick, DemoTrack, DemoWalkPlayer } from '../src';
import {
  Effect, EffectType, EngineEvent, EngineEventType, EngineSnapshot, StopProgress, StopStatus, TourPhase, TourPlan
} from '../src';
import {
  BackgroundPort, Clock, Fix, FixListener, FixSource, HapticsPort, LocationErrorListener, LocationSource, LoggerPort,
  MediaSessionPort, NotifierPort, PackLoadResult, PackRepository, PermissionPort, SpeechCapabilities, SpeechListener,
  SpeechPort, Utterance, VoicePlan, VoicePort, VoiceState
} from '../src';
import {
  ContentTier, Lang, LatLng, MapData, Narration, NarrationLength, PackManifest, Persona, Poi, PoiKind,
  ProvenanceKind, RouteData, SourceRef, Tour, TourStop
} from '../src';
import { EnVoiceStrategy, VoiceLabel } from '../src';
import { DemoControls, TourController, TourControllerDeps } from '../src';
import { Scheduler } from '../src';
import {
  DEMO_MINI_DIST_M, DEMO_MINI_DUR_S, DEMO_MINI_EVENTS, DEMO_MINI_STOPS, MiniEvent, MiniStop, demoMiniLegs,
  demoTrackMini
} from './fixtures/DemoTrackMini';

const T0: number = 1700000000000;
const SENTENCE_MS: number = 2500;          // fake speech: every sentence takes 2.5 s
const MAX_STEPS: number = 6000;            // 1 s steps; the x1 walk needs ~1250
const PERSONA: string = 'historian';
const TOUR_ID: string = 'royal-route-mini';
/** An arrival may be confirmed at most this long (track time) after the walker leaves the stop's dwell. */
const ARRIVAL_SLACK_MS: number = 10000;
/** Off-route may start/clear this long (track time) around the detour window (fixes > 35 m off the leg). */
const OFF_ROUTE_SLACK_MS: number = 30000;
/*
 * Walking pace (issue #60, fixed in core/tour). At x1 the geofence (35 m + up to 15 m accuracy allowance) is entered
 * ~25-50 s before the walker reaches a stop, so this fixture's short teaser (arrival line + 2 sentences x 2.5 s) ends
 * while the walker is still approaching. The engine then waits in silence (LINGER, `STORY_LINGER action=wait`) and
 * decides on a later fix: full once the walker has stood still for 4 s (every stop of the plain walk has a dwell).
 */

// ---------------------------------------------------------------- pack built from the fixture stops

/** The pack POI of fixture stop n (the stops are the real Royal Route POIs, the legs the pack's). */
function poiId(n: number): string {
  const s: MiniStop | undefined = DEMO_MINI_STOPS.find((m: MiniStop) => m.n === n);
  return s === undefined ? `poi_demo_stop_${n}` : s.poiId;
}

function stopOf(id: string): MiniStop | undefined {
  return DEMO_MINI_STOPS.find((s: MiniStop) => poiId(s.n) === id);
}

function stopIds(): string[] {
  return DEMO_MINI_STOPS.map((s: MiniStop) => poiId(s.n));
}

function eventOf(kind: string): MiniEvent {
  return DEMO_MINI_EVENTS.find((e: MiniEvent) => e.kind === kind) as MiniEvent;
}

function packPois(): Poi[] {
  const out: Poi[] = [];
  for (const s of DEMO_MINI_STOPS) {
    const p: Poi = {
      id: poiId(s.n), kind: PoiKind.CHURCH, lat: s.lat, lng: s.lng, x: 0, y: 0, names: { en: s.name, pl: s.name },
      importance: 1, tier: ContentTier.REVIEWED_HISTORIAN, triggerRadiusM: s.triggerRadiusM, sourceIds: ['src_test']
    };
    out.push(p);
  }
  return out;
}

function packTour(): Tour {
  const stops: TourStop[] = DEMO_MINI_STOPS.map((s: MiniStop) => {
    const ts: TourStop = { poiId: poiId(s.n), dwellS: 60, prize: 3 };
    return ts;
  });
  const t: Tour = {
    id: TOUR_ID, personaId: PERSONA, titles: { en: 'Royal Route (stops 7-11)' }, summaries: { en: 'Replay fixture' },
    stops: stops, fixedStartPoiId: poiId(DEMO_MINI_STOPS[0].n),
    fixedEndPoiId: poiId(DEMO_MINI_STOPS[DEMO_MINI_STOPS.length - 1].n), estMinutes: 20
  };
  return t;
}

/** The pack's walking matrix and legs between the fixture stops (routes.json, written into the fixture). */
function packRoutes(): RouteData {
  const r: RouteData = {
    nodeIds: stopIds(), distancesM: DEMO_MINI_DIST_M, durationsS: DEMO_MINI_DUR_S, detourFactor: 1.25,
    legs: demoMiniLegs()
  };
  return r;
}

function teaserText(n: number, i: number): string {
  return `Stop ${n} teaser sentence ${i}.`;
}

function fullText(n: number, i: number): string {
  return `Stop ${n} full sentence ${i}.`;
}

function narration(s: MiniStop, len: NarrationLength): Narration {
  const sentences: string[] = [];
  const count: number = len === NarrationLength.TEASER ? 2 : 3;
  for (let i = 1; i <= count; i++) {
    sentences.push(len === NarrationLength.TEASER ? teaserText(s.n, i) : fullText(s.n, i));
  }
  const n: Narration = {
    id: `${poiId(s.n)}:${PERSONA}:en:${len}`, poiId: poiId(s.n), personaId: PERSONA, lang: Lang.EN, length: len,
    sentences: sentences, tier: ContentTier.REVIEWED_HISTORIAN, sources: ['src_test'], claims: [],
    generatedBy: { kind: ProvenanceKind.HUMAN, at: '2026-10-03T00:00:00Z' },
    validation: { status: 'pass', checks: ['fixture'], validatorVersion: 1 }
  };
  return n;
}

function narrationLookup(poi: string, len: NarrationLength): Narration | undefined {
  const s: MiniStop | undefined = stopOf(poi);
  if (s === undefined || len === NarrationLength.DEEP) {
    return undefined;
  }
  return narration(s, len);
}

function voicePlan(text: boolean): VoicePlan {
  const v: VoicePlan = {
    textLang: Lang.EN, speechMode: text ? 'text' : 'voice', engineLocale: text ? '' : 'zh-CN', person: text ? 0 : 13,
    languageContext: text ? '' : 'en-US', label: text ? VoiceLabel.TEXT_ONLY_USER : VoiceLabel.FALLBACK_ZH_READS_EN,
    reason: 'replay'
  };
  return v;
}

function invalidOrigin(): LatLng {
  const o: LatLng = { lat: Number.NaN, lng: Number.NaN };
  return o;
}

/** The real planner on the fixture pack, from the tour's own start (as on the emulator: Beijing is out of area). */
function heldKarpPlan(): TourPlan {
  const pack: CityPack = { pois: packPois(), routes: packRoutes() };
  const inputs: PlanInputs = buildCostInputs(pack, packTour(), stopIds(), invalidOrigin());
  return planRoute(inputs, 0);
}

// ---------------------------------------------------------------- observations shared by both layers

class LogLine {
  code: string;
  kv: string;
  trackMs: number;      // track time of the sample the walker was on when the line was logged

  constructor(code: string, kv: string, trackMs: number) {
    this.code = code;
    this.kv = kv;
    this.trackMs = trackMs;
  }
}

/** One sentence the user heard (voice) or read (text-only caption). */
class Heard {
  id: string;
  itemId: string;
  index: number;
  text: string;

  constructor(u: Utterance) {
    this.id = u.id;
    this.itemId = u.itemId;
    const rest: string = u.id.substring(u.itemId.length + 1);
    const hash: number = rest.indexOf('#');
    this.index = parseInt(hash >= 0 ? rest.substring(0, hash) : rest, 10);
    this.text = u.text;
  }
}

function kvOf(kv: string, key: string): string {
  for (const part of kv.split(' ')) {
    if (part.indexOf(`${key}=`) === 0) {
      return part.substring(key.length + 1);
    }
  }
  return '';
}

function inWindow(ms: number, e: MiniEvent): boolean {
  return ms >= e.fromMs && ms <= e.toMs;
}

function stopNumber(id: string): string {
  const s: MiniStop | undefined = stopOf(id);
  return s === undefined ? '?' : `${s.n}`;
}

class Observed {
  logs: LogLine[] = [];
  heard: Heard[] = [];
  violations: string[] = [];
  stopSpeech: number = 0;
  replanRequests: number = 0;
  offRouteSnapshots: number = 0;
  demoHoldSeen: boolean = false;
  probeFixes: number = 0;
  probeTriggerGrade: number = 0;

  lines(code: string): LogLine[] {
    return this.logs.filter((l: LogLine) => l.code === code);
  }

  count(code: string, part: string): number {
    return this.lines(code).filter((l: LogLine) => l.kv.indexOf(part) >= 0).length;
  }

  enteredIds(): string[] {
    return this.lines('POI_ENTER').map((l: LogLine) => kvOf(l.kv, 'id'));
  }

  /** POI ids that got a FULL_STORY item (the engine's "linger => full" decision). */
  fullStoryIds(): string[] {
    return this.lines('STORY_QUEUE').filter((l: LogLine) => kvOf(l.kv, 'kind') === 'fullStory')
      .map((l: LogLine) => kvOf(l.kv, 'poi'));
  }

  teaserOnlyIds(): string[] {
    return this.lines('STORY_SKIP_MOVING').map((l: LogLine) => kvOf(l.kv, 'poi'));
  }

  /** NAV_CUE lines of spoken-style cues (not the snap lines). */
  navCues(kind: string): LogLine[] {
    return this.lines('NAV_CUE').filter((l: LogLine) => kvOf(l.kv, 'kind') === kind);
  }

  /** A fix accepted by the probe FixFilter (same thresholds the engine applies). */
  probe(r: FilteredFix, trackMs: number): void {
    this.probeFixes++;
    if (r.triggerGrade) {
      this.probeTriggerGrade++;
    }
  }

  /**
   * Order invariant, checked after every event: the stops already visited (VISITED / TEASER_ONLY) are a prefix of the
   * planned order, i.e. no later stop is ever marked visited while an earlier one is still open.
   */
  checkOrder(stops: StopProgress[]): void {
    let open: string = '';
    for (const p of stops) {
      const done: boolean = p.status === StopStatus.VISITED || p.status === StopStatus.TEASER_ONLY;
      if (!done && open.length === 0) {
        open = p.poiId;
      } else if (done && open.length > 0) {
        const v: string = `stop ${stopNumber(p.poiId)} visited while stop ${stopNumber(open)} is open`;
        if (this.violations.indexOf(v) < 0) {
          this.violations.push(v);
        }
      }
    }
  }

  /** Checks that every started item was heard completely, sentence by sentence, without interleaving. */
  checkSentences(): void {
    const queued: Map<string, number> = new Map<string, number>();
    for (const l of this.lines('STORY_QUEUE')) {
      queued.set(kvOf(l.kv, 'id'), parseInt(kvOf(l.kv, 'n'), 10));
    }
    const nextIdx: Map<string, number> = new Map<string, number>();
    let open: string = '';
    for (const h of this.heard) {
      const expected: number = nextIdx.has(h.itemId) ? nextIdx.get(h.itemId) as number : 0;
      if (h.index !== expected) {
        this.violations.push(`item ${h.itemId}: sentence ${h.index} heard, expected ${expected}`);
      }
      if (open.length > 0 && open !== h.itemId) {
        this.violations.push(`item ${open} cut by ${h.itemId}`);
      }
      nextIdx.set(h.itemId, h.index + 1);
      const n: number = queued.has(h.itemId) ? queued.get(h.itemId) as number : -1;
      open = h.index + 1 < n ? h.itemId : '';
    }
    nextIdx.forEach((done: number, item: string) => {
      const n: number = queued.has(item) ? queued.get(item) as number : -1;
      if (done !== n) {
        this.violations.push(`item ${item}: ${done} of ${n} sentences heard`);
      }
    });
    for (const l of this.lines('STORY_START')) {
      const id: string = kvOf(l.kv, 'id');
      if (this.count('STORY_END', `id=${id} `) !== 1) {
        this.violations.push(`item ${id}: no single STORY_END`);
      }
    }
    if (this.count('STORY_END', 'skipped=true') > 0) {
      this.violations.push('an item was skipped');
    }
  }

  summary(name: string, finished: boolean, wallS: number): string {
    const enters: string = this.lines('POI_ENTER').map((l: LogLine) =>
    `${stopNumber(kvOf(l.kv, 'id'))}@${Math.round(l.trackMs / 1000)}s`).join(',');
    return `REPLAY_SUMMARY run=${name} enter=[${enters}] full=[${this.fullStoryIds().map(stopNumber).join(',')}] ` +
      `teaserOnly=[${this.teaserOnlyIds().map(stopNumber).join(',')}] sentences=${this.heard.length} ` +
      `stories=${this.lines('STORY_START').length} violations=${this.violations.length} ` +
      `stopSpeech=${this.stopSpeech} replan=${this.lines('REPLAN').length} offRoute=${this.lines('OFF_ROUTE')
        .map((l: LogLine) => `${Math.round(l.trackMs / 1000)}s`).join(',')} navNow=${this.navCues('now').length} ` +
      `navPrepare=${this.navCues('prepare').length} ` +
      `offRouteSnaps=${this.offRouteSnapshots} locPoor=${this.lines('LOC_POOR').length} ` +
      `triggerGrade=${this.probeTriggerGrade}/${this.probeFixes} finished=${finished} simulatedS=${wallS}`;
  }
}

// ---------------------------------------------------------------- layer 1: pure engine replay

class EngineReplay {
  readonly text: boolean;
  readonly speed: number;
  readonly trackStamps: boolean;      // true: fix timestamps = track time (x1); false: wall clock (DemoWalkSource)
  readonly track: DemoTrack = demoTrackMini();
  readonly player: DemoWalkPlayer;
  readonly probe: FixFilter = new FixFilter();
  readonly obs: Observed = new Observed();
  st: TourState;
  plan: TourPlan;
  t: number = T0;
  trackMs: number = 0;
  inFlight: Utterance | undefined = undefined;
  dueMs: number = 0;
  ended: boolean = false;
  steps: number = 0;
  private lastShown: string = '';

  constructor(text: boolean, speed: number, trackStamps: boolean) {
    this.text = text;
    this.speed = speed;
    this.trackStamps = trackStamps;
    this.player = new DemoWalkPlayer(this.track);
    this.player.reset(T0);
    const input: TourInput = {
      tour: packTour(), pois: packPois(), lang: Lang.EN, personaId: PERSONA,
      narration: (id: string, len: NarrationLength): Narration | undefined => narrationLookup(id, len),
      voice: voicePlan(text), adaptiveLength: true, spokenDirections: true, source: FixSource.DEMO,
      legs: demoMiniLegs()
    };
    this.st = TourEngine.init(input, new TourConfig());
    this.plan = heldKarpPlan();
  }

  /** REQUEST_REPLAN, as TourController.replan(): the planner over the open stops from the current fix. */
  replan(nowMs: number): void {
    const open: string[] = TourEngine.snapshot(this.st).stops
      .filter((s: StopProgress) => s.status === StopStatus.PENDING || s.status === StopStatus.APPROACHING)
      .map((s: StopProgress) => s.poiId);
    const f: Fix | undefined = this.st.lastFix;
    const origin: LatLng = f === undefined ? invalidOrigin() : { lat: f.lat, lng: f.lng };
    const pack: CityPack = { pois: packPois(), routes: packRoutes() };
    const p: TourPlan = planRoute(buildCostInputs(pack, packTour(), open, origin), 0);
    const ev: EngineEvent = { type: EngineEventType.PLAN_READY, nowMs: nowMs, plan: p };
    this.dispatch(ev);
  }

  /** "A story is playing" (TourController.storyActive), the Demo walk hold predicate. */
  storyActive(): boolean {
    return this.st.phase === TourPhase.AT_STOP && this.st.activeIdx >= 0;
  }

  dispatch(ev: EngineEvent): void {
    const r: StepResult = TourEngine.reduce(this.st, ev);
    this.st = r.state;
    let replan: boolean = false;
    for (const fx of r.effects) {
      this.execute(fx, ev.nowMs);
      replan = replan || fx.type === EffectType.REQUEST_REPLAN;
    }
    if (replan) {
      this.replan(ev.nowMs);
    }
    if (this.text) {
      const u: Utterance | undefined = this.st.queue.inFlight();
      if (u !== undefined && u.id !== this.lastShown) {
        this.lastShown = u.id;
        this.obs.heard.push(new Heard(u));
      }
    }
    const snap: EngineSnapshot = TourEngine.snapshot(this.st);
    if (snap.offRoute) {
      this.obs.offRouteSnapshots++;
    }
    this.obs.checkOrder(snap.stops);
  }

  execute(fx: Effect, nowMs: number): void {
    switch (fx.type) {
      case EffectType.SPEAK:
        if (fx.utterance !== undefined) {
          if (this.text) {
            this.obs.violations.push(`SPEAK in text-only mode: ${fx.utterance.id}`);
          }
          if (this.inFlight !== undefined) {
            this.obs.violations.push(`SPEAK ${fx.utterance.id} while ${this.inFlight.id} is still speaking`);
          }
          this.inFlight = fx.utterance;
          this.dueMs = nowMs + SENTENCE_MS;
          this.obs.heard.push(new Heard(fx.utterance));
        }
        break;
      case EffectType.STOP_SPEECH:
        this.obs.stopSpeech++;
        if (fx.afterCurrent !== true && this.inFlight !== undefined) {
          this.obs.violations.push(`STOP_SPEECH cut ${this.inFlight.id}`);
          this.inFlight = undefined;
        }
        break;
      case EffectType.REQUEST_REPLAN:
        this.obs.replanRequests++;
        break;
      case EffectType.LOG:
        this.obs.logs.push(new LogLine(fx.logCode === undefined ? '' : fx.logCode,
          fx.logKv === undefined ? '' : fx.logKv, this.trackMs));
        break;
      default:
        break;
    }
  }

  simple(type: EngineEventType, nowMs: number): EngineEvent {
    const ev: EngineEvent = { type: type, nowMs: nowMs };
    return ev;
  }

  idle(): boolean {
    return !this.st.queue.isBusy() && this.st.queue.size() === 0;
  }

  run(): EngineReplay {
    this.dispatch(this.simple(EngineEventType.START_PLANNING, this.t));
    const ready: EngineEvent = { type: EngineEventType.PLAN_READY, nowMs: this.t, plan: this.plan };
    this.dispatch(ready);
    this.dispatch(this.simple(EngineEventType.START_TOUR, this.t));
    for (this.steps = 0; this.steps < MAX_STEPS; this.steps++) {
      this.t += 1000;
      while (this.inFlight !== undefined && this.dueMs <= this.t) {
        const done: EngineEvent = {
          type: EngineEventType.UTTERANCE_DONE, nowMs: this.dueMs, utteranceId: this.inFlight.id
        };
        this.inFlight = undefined;
        this.dispatch(done);
      }
      this.dispatch(this.simple(EngineEventType.TICK, this.t));
      if (!this.ended) {
        const tick: DemoTick = this.player.tick(1000 * this.speed, this.storyActive());
        this.ended = tick.ended;
        this.trackMs = this.track.fixes[tick.index].tRelMs;
        const f: Fix = tick.fix;
        if (!this.trackStamps) {
          f.timestampMs = this.t;            // DemoWalkSource default: wall-clock stamps
        }
        this.obs.probe(this.probe.accept(f), this.trackMs);
        const ev: EngineEvent = { type: EngineEventType.FIX, nowMs: f.timestampMs, fix: f };
        this.dispatch(ev);
      }
      if (this.st.phase === TourPhase.FINISHED && this.idle() && this.inFlight === undefined) {
        break;
      }
    }
    this.obs.checkSentences();
    return this;
  }

  statusOf(id: string): StopStatus | undefined {
    const p: StopProgress | undefined = TourEngine.snapshot(this.st).stops.find((s: StopProgress) => s.poiId === id);
    return p === undefined ? undefined : p.status;
  }

  summary(name: string): string {
    return this.obs.summary(name, this.st.phase === TourPhase.FINISHED, this.steps);
  }
}

/** Every planned stop entered exactly once, in the planned order, each on its own stretch of the walk. */
function assertPlannedOrder(obs: Observed): void {
  expect(obs.enteredIds().join(',')).toBe(stopIds().join(','));
  // never a later stop visited while an earlier one is open (checked after every event)
  expect(obs.violations.filter((v: string) => v.indexOf(' visited while ') >= 0).join(' | ')).toBe('');
}

/** The assertions every walked run must pass (both speech modes, all speeds, both layers). */
function assertJuryOutcomes(obs: Observed, finalStatus: (id: string) => StopStatus | undefined): void {
  assertPlannedOrder(obs);
  // each arrival on the right stretch of the walk (after leaving the previous stop, before leaving this one);
  // none during the detour
  for (const l of obs.lines('POI_ENTER')) {
    const s: MiniStop = stopOf(kvOf(l.kv, 'id')) as MiniStop;
    const i: number = DEMO_MINI_STOPS.indexOf(s);
    const after: number = i > 0 ? DEMO_MINI_STOPS[i - 1].departMs : -1;
    expect(l.trackMs > after && l.trackMs <= s.departMs + ARRIVAL_SLACK_MS).toBe(true);
    expect(inWindow(l.trackMs, eventOf('detour'))).toBe(false);
  }
  // story length: the walker dwells at every stop, so every stop gets the full story (at x1 too, issue #60)
  expect(DEMO_MINI_STOPS.every((s: MiniStop) => s.mode === 'dwell')).toBe(true);
  expect(obs.fullStoryIds().join(',')).toBe(stopIds().join(','));
  expect(obs.teaserOnlyIds().length).toBe(0);
  for (const id of stopIds()) {
    expect(finalStatus(id)).toBe(StopStatus.VISITED);
  }
  // no story interrupted mid-sentence
  expect(obs.violations.join(' | ')).toBe('');
  expect(obs.stopSpeech).toBe(0);
  expect(obs.lines('STORY_START').length > 0).toBe(true);
  // every story was heard to its last sentence: the teaser and the full story at every stop
  for (const s of DEMO_MINI_STOPS) {
    expect(obs.heard.some((h: Heard) => h.text === teaserText(s.n, 2))).toBe(true);
    expect(obs.heard.some((h: Heard) => h.text === fullText(s.n, 3))).toBe(true);
  }
  // finished (exactly one engine transition; the controller's TEARDOWN line is from=finished)
  expect(obs.lines('STATE').filter((l: LogLine) => kvOf(l.kv, 'to') === 'finished' && kvOf(l.kv, 'from') !== 'finished')
    .length).toBe(1);
  // no lost-GPS episode, no degraded fix: the plain walk is trigger-grade throughout
  expect(obs.lines('LOC_LOST').length).toBe(0);
  expect(obs.probeFixes > 0).toBe(true);
  expect(obs.probeTriggerGrade).toBe(obs.probeFixes);
  expect(obs.lines('LOC_POOR').length).toBe(0);
  assertTurnByTurn(obs);
}

/**
 * A9: turn cues fire on the walk, each once; the injected ~80 m detour (and only it) is OFF_ROUTE -> REPLAN ->
 * ON_ROUTE. Holds for every run (x1 track stamps, x4/x8 wall-clock stamps, text-only, the controller).
 */
function assertTurnByTurn(obs: Observed): void {
  const now: LogLine[] = obs.navCues('now');
  expect(now.length >= 4).toBe(true);
  const keys: string[] = obs.lines('NAV_CUE').filter((l: LogLine) => kvOf(l.kv, 'kind') !== 'snap')
    .map((l: LogLine) => `${kvOf(l.kv, 'leg')}:${kvOf(l.kv, 'step')}:${kvOf(l.kv, 'kind')}`);
  expect(new Set<string>(keys).size).toBe(keys.length);              // every cue once
  expect(obs.lines('NAV_CUE').every((l: LogLine) => kvOf(l.kv, 'src') === 'demo')).toBe(true);
  expect(obs.lines('NAV_CUE').filter((l: LogLine) => kvOf(l.kv, 'kind') !== 'snap')
    .every((l: LogLine) => kvOf(l.kv, 'spoken') === '1')).toBe(true);
  // a turn cue was really said (or captioned) to the end
  expect(obs.heard.some((h: Heard) => h.text.indexOf('Now ') === 0)).toBe(true);
  // the detour: exactly one off-route episode, inside its window, then the re-plan, then back on the route
  const det: MiniEvent = eventOf('detour');
  const off: LogLine[] = obs.lines('OFF_ROUTE');
  expect(off.length).toBe(1);
  expect(off[0].trackMs >= det.fromMs && off[0].trackMs <= det.toMs).toBe(true);
  expect(kvOf(off[0].kv, 'leg')).toBe(`${poiId(7)}>${poiId(8)}`);
  expect(kvOf(off[0].kv, 'src')).toBe('demo');
  expect(inOrder(obs, [['OFF_ROUTE', 'leg='], ['REPLAN', 'changed=0'], ['ON_ROUTE', 'leg=']]) >= 0).toBe(true);
  const re: LogLine[] = obs.lines('REPLAN');
  expect(re.length).toBe(1);
  expect(kvOf(re[0].kv, 'to')).toBe(poiId(8));
  const on: LogLine[] = obs.lines('ON_ROUTE');
  expect(on.length).toBe(1);
  expect(on[0].trackMs >= det.fromMs && on[0].trackMs <= det.toMs + OFF_ROUTE_SLACK_MS).toBe(true);
  expect(obs.offRouteSnapshots > 0).toBe(true);
  expect(obs.heard.some((h: Heard) => h.text === 'You\'ve left the route.')).toBe(true);
}

/**
 * x1 only (issue #60): the teaser ended before the walker reached stops 8-11, so the engine waited (LINGER) and
 * switched to the full story only once the walker stood still there; nobody was judged to be walking past.
 */
function assertWalkingPaceLinger(obs: Observed): void {
  const waited: string[] = obs.lines('STORY_LINGER').filter((l: LogLine) => kvOf(l.kv, 'action') === 'wait')
    .map((l: LogLine) => stopNumber(kvOf(l.kv, 'poi')));
  expect(waited.join(',')).toBe('8,9,10,11');
  const stillFull: string[] = obs.lines('STORY_LINGER')
    .filter((l: LogLine) => kvOf(l.kv, 'action') === 'full' && kvOf(l.kv, 'reason') === 'still')
    .map((l: LogLine) => stopNumber(kvOf(l.kv, 'poi')));
  expect(stillFull.join(',')).toBe('8,9,10,11');
  for (const l of obs.lines('STORY_LINGER')) {
    if (kvOf(l.kv, 'action') === 'full') {     // the full story starts at the stop, not on the approach
      const s: MiniStop = stopOf(kvOf(l.kv, 'poi')) as MiniStop;
      expect(l.trackMs >= s.arrivalMs && l.trackMs <= s.departMs).toBe(true);
    }
  }
  expect(obs.lines('STORY_SKIP_MOVING').length).toBe(0);
}

// ---------------------------------------------------------------- layer 2: TourController with fake ports

class ManualClock implements Clock {
  t: number = T0;

  nowMs(): number {
    return this.t;
  }
}

class Job {
  id: number;
  at: number;
  period: number;
  fn: () => void;

  constructor(id: number, at: number, period: number, fn: () => void) {
    this.id = id;
    this.at = at;
    this.period = period;
    this.fn = fn;
  }
}

class ManualScheduler implements Scheduler {
  private clock: ManualClock;
  private jobs: Job[] = [];
  private seq: number = 0;

  constructor(clock: ManualClock) {
    this.clock = clock;
  }

  after(ms: number, fn: () => void): number {
    this.seq++;
    this.jobs.push(new Job(this.seq, this.clock.t + Math.max(0, ms), 0, fn));
    return this.seq;
  }

  every(ms: number, fn: () => void): number {
    this.seq++;
    this.jobs.push(new Job(this.seq, this.clock.t + ms, ms, fn));
    return this.seq;
  }

  cancel(id: number): void {
    this.jobs = this.jobs.filter((j: Job) => j.id !== id);
  }

  count(): number {
    return this.jobs.length;
  }

  /** Fires every job due within `ms`, in time order (ties by creation), moving the clock along. */
  advance(ms: number): void {
    const end: number = this.clock.t + ms;
    for (let guard = 0; guard < 100000; guard++) {
      let next: Job | undefined = undefined;
      for (const j of this.jobs) {
        if (j.at <= end && (next === undefined || j.at < next.at || (j.at === next.at && j.id < next.id))) {
          next = j;
        }
      }
      if (next === undefined) {
        break;
      }
      const due: Job = next;
      this.clock.t = Math.max(this.clock.t, due.at);
      if (due.period > 0) {
        due.at += due.period;
      } else {
        this.jobs = this.jobs.filter((j: Job) => j.id !== due.id);
      }
      due.fn();
    }
    this.clock.t = end;
  }
}

/** LoggerPort that records `EVENT k=v` lines with the track time of the demo walker. */
class RecordingLog implements LoggerPort {
  readonly obs: Observed;
  trackMs: () => number = () => 0;

  constructor(obs: Observed) {
    this.obs = obs;
  }

  info(event: string, kv: string): void {
    this.obs.logs.push(new LogLine(event, kv, this.trackMs()));
  }

  warn(event: string, kv: string): void {
    this.info(event, kv);
  }

  error(event: string, kv: string): void {
    this.info(event, kv);
  }
}

class ReplaySpeech implements SpeechPort {
  private readonly sched: ManualScheduler;
  private readonly obs: Observed;
  private listener: SpeechListener | undefined = undefined;
  private inFlight: Utterance | undefined = undefined;

  constructor(sched: ManualScheduler, obs: Observed) {
    this.sched = sched;
    this.obs = obs;
  }

  init(): Promise<SpeechCapabilities> {
    const c: SpeechCapabilities = { en: VoiceState.DOWNLOADABLE, zh: VoiceState.INSTALLED };
    return Promise.resolve(c);
  }

  setListener(l: SpeechListener): void {
    this.listener = l;
  }

  speak(u: Utterance): void {
    if (this.inFlight !== undefined) {
      this.obs.violations.push(`speak ${u.id} while ${this.inFlight.id} is still speaking`);
    }
    this.inFlight = u;
    this.obs.heard.push(new Heard(u));
    const l: SpeechListener | undefined = this.listener;
    if (l === undefined) {
      return;
    }
    l.onUtteranceStart(u.id);
    const id: string = u.id;
    this.sched.after(SENTENCE_MS, () => {
      if (this.inFlight !== undefined && this.inFlight.id === id) {
        this.inFlight = undefined;
        l.onUtteranceDone(id);
      }
    });
  }

  prefetch(u: Utterance): void {
  }

  stopNow(): void {
    this.obs.stopSpeech++;
    if (this.inFlight !== undefined) {
      this.obs.violations.push(`stopNow cut ${this.inFlight.id}`);
    }
    this.inFlight = undefined;
  }

  pause(): void {
  }

  resume(): void {
  }

  isSpeaking(): boolean {
    return this.inFlight !== undefined;
  }
}

class ReplayVoice implements VoicePort {
  capabilities(): Promise<SpeechCapabilities> {
    const c: SpeechCapabilities = { en: VoiceState.DOWNLOADABLE, zh: VoiceState.INSTALLED };
    return Promise.resolve(c);
  }

  plan(textLang: Lang): VoicePlan {
    return voicePlan(false);
  }

  downloadEnglish(onProgress: (pct: number) => void): Promise<boolean> {
    return Promise.resolve(false);
  }

  setStrategy(s: EnVoiceStrategy): void {
  }
}

class ReplayPack implements PackRepository {
  load(): Promise<PackLoadResult> {
    const m: PackManifest = {
      schemaVersion: 1, packId: 'replay-mini', version: '0', builtAt: '2026-10-03T00:00:00Z',
      origin: { lat: 50.06143, lng: 19.93658 }, bbox: [50.0525, 19.929, 50.0675, 19.947], files: [],
      counts: {
        pois: DEMO_MINI_STOPS.length, narrations_en: DEMO_MINI_STOPS.length * 2, narrations_pl: 0, narrations_zh: 0,
        legs: demoMiniLegs().length
      },
      licenses: []
    };
    const r: PackLoadResult = { ok: true, manifest: m, issues: [] };
    return Promise.resolve(r);
  }

  pois(): Poi[] {
    return packPois();
  }

  poi(id: string): Poi | undefined {
    return packPois().find((p: Poi) => p.id === id);
  }

  tours(): Tour[] {
    return [packTour()];
  }

  personas(): Persona[] {
    const p: Persona = {
      id: PERSONA, names: { en: 'Historian' }, voices: [{ lang: Lang.EN, person: 8 }, { lang: Lang.ZH, person: 13 }],
      speed: 1, pitch: 1
    };
    return [p];
  }

  routes(): RouteData {
    return packRoutes();
  }

  map(level: string): MapData {
    const d: MapData = { level: level, origin: { lat: 50.0617, lng: 19.9373 }, bounds: [], layers: [] };
    return d;
  }

  narration(poi: string, personaId: string, lang: Lang, len: NarrationLength): Narration | undefined {
    return lang === Lang.EN ? narrationLookup(poi, len) : undefined;
  }

  source(id: string): SourceRef | undefined {
    return undefined;
  }
}

/** DemoWalkSource without @kit: a 1 s timer, DemoWalkPlayer at the chosen speed, wall-clock stamps, hold predicate. */
class ReplayDemoSource implements LocationSource, DemoControls {
  readonly kind: FixSource = FixSource.DEMO;
  readonly track: DemoTrack = demoTrackMini();
  readonly player: DemoWalkPlayer;
  private readonly sched: ManualScheduler;
  private readonly clock: ManualClock;
  private readonly probe: FixFilter = new FixFilter();
  private readonly obs: Observed;
  private timer: number = -1;
  private mult: number = 1;
  private hold: () => boolean = () => false;
  private holding: boolean = false;
  private ended: boolean = false;
  private onFix: FixListener | undefined = undefined;
  private lastTs: number = 0;
  trackMs: number = 0;

  /** Wall-clock stamp, strictly increasing like DemoWalkSource.emit (a jump fix shares the second of a tick). */
  private stamp(): number {
    this.lastTs = Math.max(this.clock.t, this.lastTs + 1);
    return this.lastTs;
  }

  constructor(sched: ManualScheduler, clock: ManualClock, obs: Observed) {
    this.sched = sched;
    this.clock = clock;
    this.obs = obs;
    this.player = new DemoWalkPlayer(this.track);
    this.player.reset(clock.t);
  }

  start(onFix: FixListener, onError: LocationErrorListener): Promise<void> {
    this.stop();
    this.onFix = onFix;
    this.timer = this.sched.every(1000, () => {
      if (this.ended) {
        return;
      }
      const tick: DemoTick = this.player.tick(1000 * this.mult, this.hold());
      this.holding = tick.holding;
      this.ended = tick.ended;
      this.trackMs = this.track.fixes[tick.index].tRelMs;
      const f: Fix = tick.fix;
      f.timestampMs = this.stamp();
      this.obs.probe(this.probe.accept(f), this.trackMs);
      onFix(f);
    });
    return Promise.resolve();
  }

  stop(): void {
    if (this.timer >= 0) {
      this.sched.cancel(this.timer);
      this.timer = -1;
    }
  }

  isRunning(): boolean {
    return this.timer >= 0;
  }

  setSpeed(mult: number): void {
    this.mult = mult;
  }

  jumpToNextStop(): void {
    this.player.jumpToNextStop();
  }

  /** As DemoWalkSource.jumpToStop: to the stop's hold segment (by POI, else planned index + 1), emitted at once. */
  jumpToStop(poiId: string, plannedIdx: number): void {
    const byPoi: number = this.player.stopNumberOf(poiId);
    if (this.player.jumpToStop(byPoi > 0 ? byPoi : plannedIdx + 1) === 0) {
      return;
    }
    this.ended = false;
    this.trackMs = this.track.fixes[this.player.index()].tRelMs;
    const f: Fix = this.player.current();
    f.timestampMs = this.stamp();
    this.obs.probe(this.probe.accept(f), this.trackMs);
    if (this.onFix !== undefined && this.timer >= 0) {
      this.onFix(f);
    }
  }

  setHoldPredicate(p: () => boolean): void {
    this.hold = p;
  }

  isHolding(): boolean {
    return this.holding;
  }

  rewind(): void {
    this.player.reset(this.clock.t);
    this.ended = false;
  }
}

class ControllerReplay {
  readonly obs: Observed = new Observed();
  readonly clock: ManualClock = new ManualClock();
  readonly sched: ManualScheduler;
  readonly log: RecordingLog;
  readonly demo: ReplayDemoSource;
  readonly ctrl: TourController;
  seconds: number = 0;

  constructor() {
    this.sched = new ManualScheduler(this.clock);
    this.log = new RecordingLog(this.obs);
    this.demo = new ReplayDemoSource(this.sched, this.clock, this.obs);
    this.log.trackMs = () => this.demo.trackMs;
    const deps: TourControllerDeps = {
      pack: new ReplayPack(), speech: new ReplaySpeech(this.sched, this.obs), voice: new ReplayVoice(), log: this.log,
      clock: this.clock, scheduler: this.sched,
      sourceFor: (kind: FixSource): LocationSource | undefined => kind === FixSource.DEMO ? this.demo : undefined,
      demoControls: (): DemoControls | undefined => this.demo,
      background: (): BackgroundPort | undefined => undefined,
      media: (): MediaSessionPort | undefined => undefined,
      notifier: (): NotifierPort | undefined => undefined,
      haptics: (): HapticsPort | undefined => undefined,
      permissions: (): PermissionPort | undefined => undefined
    };
    this.ctrl = new TourController(deps);
  }

  /** Runs one wall second at a time until the controller tore the tour down (or MAX_STEPS). */
  walk(): void {
    for (this.seconds = 0; this.seconds < MAX_STEPS && this.ctrl.isRunning(); this.seconds++) {
      this.sched.advance(1000);
      const s: EngineSnapshot = this.ctrl.current();
      if (s.offRoute) {
        this.obs.offRouteSnapshots++;
      }
      if (s.platform.demoHold) {
        this.obs.demoHoldSeen = true;
      }
      this.obs.checkOrder(s.stops);
    }
    this.obs.checkSentences();
  }

  /**
   * Skip at every stop: each second at a stop whose story has started, press Skip (as the Now Walking button does).
   * Returns "<new current stop n>:<walker's stop n>" right after each skip that moved the tour on.
   */
  walkSkipping(): string[] {
    const jumps: string[] = [];
    for (this.seconds = 0; this.seconds < MAX_STEPS && this.ctrl.isRunning(); this.seconds++) {
      this.sched.advance(1000);
      const s: EngineSnapshot = this.ctrl.current();
      this.obs.checkOrder(s.stops);
      if (s.platform.demoHold) {
        this.obs.demoHoldSeen = true;
      }
      if (s.phase !== TourPhase.AT_STOP || s.currentStopIdx < 0) {
        continue;
      }
      const here: string = s.stops[s.currentStopIdx].poiId;
      if (this.obs.count('STORY_START', `poi=${here}`) === 0) {
        continue;
      }
      this.ctrl.skip();                                    // the stop's story (or the line still ahead of it)
      const after: EngineSnapshot = this.ctrl.current();
      if (after.phase !== TourPhase.FINISHED && after.currentStopIdx >= 0 && after.currentStopIdx !== s.currentStopIdx) {
        // the tour moved on: the walker was jumped there (and, standing at the stop, is usually entered at once)
        const target: string = after.stops[after.currentStopIdx].poiId;
        jumps.push(`${stopNumber(target)}:${this.demo.player.currentStop()}`);
      }
    }
    return jumps;
  }

  statusOf(id: string): StopStatus | undefined {
    const p: StopProgress | undefined = this.ctrl.current().stops.find((s: StopProgress) => s.poiId === id);
    return p === undefined ? undefined : p.status;
  }
}

/** Index of the last matched log line if every [code, part] appears in this order; -1 if one is missing. */
function inOrder(obs: Observed, steps: string[][]): number {
  let at: number = -1;
  for (const s of steps) {
    let found: number = -1;
    for (let i = at + 1; i < obs.logs.length; i++) {
      if (obs.logs[i].code === s[0] && obs.logs[i].kv.indexOf(s[1]) >= 0) {
        found = i;
        break;
      }
    }
    if (found < 0) {
      return -1;
    }
    at = found;
  }
  return at;
}

function replayTest() {
  describe('Replay', () => {
    it('fixture_and_plan: DemoTrackMini is simulated, Held-Karp plans stops 7-11 in walking order', () => {
      const t: DemoTrack = demoTrackMini();
      expect(t.simulated).toBe(true);
      expect(t.fixes.length > 1000).toBe(true);
      expect(DEMO_MINI_STOPS.length).toBe(5);
      // plain walk: a dwell (hold segment) at every stop, in the planned order, one segment per stop
      expect(DEMO_MINI_STOPS.every((s: MiniStop) => s.mode === 'dwell')).toBe(true);
      expect(new DemoWalkPlayer(t).holdStops().join(',')).toBe('7,8,9,10,11');
      // the track's stop list maps the pack POIs to the hold segments (what Skip jumps by)
      for (const s of DEMO_MINI_STOPS) {
        expect(new DemoWalkPlayer(t).stopNumberOf(s.poiId)).toBe(s.n);
      }
      // one scripted moment only: the detour; GPS-like accuracy everywhere (trigger-grade, <= 40 m)
      expect(DEMO_MINI_EVENTS.map((e: MiniEvent) => e.kind).join(',')).toBe('detour');
      expect(t.fixes.every((f: DemoFix) => f.accuracyM <= 10)).toBe(true);
      const p: TourPlan = heldKarpPlan();
      expect(p.algo).toBe('heldkarp');
      expect(p.order.join(',')).toBe(stopIds().join(','));
    });

    it('voice_x1: track-time replay through FixFilter + TourEngine gives the jury outcomes', () => {
      const r: EngineReplay = new EngineReplay(false, 1, true).run();
      console.info(r.summary('engine-voice-x1'));
      assertJuryOutcomes(r.obs, (id: string) => r.statusOf(id));
      assertWalkingPaceLinger(r.obs);
      expect(r.st.phase).toBe(TourPhase.FINISHED);
      expect(r.idle()).toBe(true);
      // the finish lines are the last thing heard
      const starts: LogLine[] = r.obs.lines('STORY_START');
      expect(r.obs.heard[r.obs.heard.length - 1].itemId).toBe(kvOf(starts[starts.length - 1].kv, 'id'));
    });

    it('voice_x8: wall-clock stamps at x8 (the emulator demo setting) keep the same outcomes', () => {
      const r: EngineReplay = new EngineReplay(false, 8, false).run();
      console.info(r.summary('engine-voice-x8'));
      assertJuryOutcomes(r.obs, (id: string) => r.statusOf(id));
      expect(r.st.phase).toBe(TourPhase.FINISHED);
    });

    it('voice_x4: wall-clock stamps at x4 (the other demo speed) keep the same outcomes', () => {
      const r: EngineReplay = new EngineReplay(false, 4, false).run();
      console.info(r.summary('engine-voice-x4'));
      assertJuryOutcomes(r.obs, (id: string) => r.statusOf(id));
      expect(r.st.phase).toBe(TourPhase.FINISHED);
    });

    it('text_only_x1: no SPEAK at all, captions paced by TICK, same outcomes', () => {
      const r: EngineReplay = new EngineReplay(true, 1, true).run();
      console.info(r.summary('engine-text-x1'));
      assertJuryOutcomes(r.obs, (id: string) => r.statusOf(id));
      assertWalkingPaceLinger(r.obs);
      expect(r.st.phase).toBe(TourPhase.FINISHED);
      expect(r.inFlight === undefined).toBe(true);
      expect(r.obs.count('STORY_START', 'mode=text')).toBe(r.obs.lines('STORY_START').length);
      expect(r.obs.count('STORY_START', 'mode=voice')).toBe(0);
    });

    it('deterministic: two replays produce the identical log', () => {
      const a: EngineReplay = new EngineReplay(false, 1, true).run();
      // Same plan object: TourPlan.ms is the planner's wall-clock run time (logged in ROUTE_PLAN), 0 or 1 ms
      // depending on machine load, which made this case flaky. The engine replay itself must be identical.
      const b: EngineReplay = new EngineReplay(false, 1, true);
      b.plan = a.plan;
      b.run();
      // A9: the mid-tour re-plan runs the planner again; its wall-clock `ms=` in the REPLAN line is not replayed.
      const text = (r: EngineReplay): string => r.obs.logs.map((l: LogLine) => `${l.code} ${l.kv}`)
        .join('\n').replace(/ ms=[0-9]+/g, ' ms=_');
      expect(a.obs.logs.length > 50).toBe(true);
      expect(text(a)).toBe(text(b));
    });

    it('controller_x8: TourController + demo source at x8, logs in smoke order, same outcomes', async () => {
        const r: ControllerReplay = new ControllerReplay();
        await r.ctrl.setSource(FixSource.DEMO);
        const p: TourPlan = await r.ctrl.plan(TOUR_ID, 0);
        expect(p.algo).toBe('heldkarp');
        r.ctrl.setDemoSpeed(8);
        await r.ctrl.start();
        expect(r.ctrl.isRunning()).toBe(true);
        r.walk();
        console.info(r.obs.summary('controller-voice-x8', r.ctrl.current().phase === TourPhase.FINISHED, r.seconds));
        expect(r.ctrl.isRunning()).toBe(false);
        expect(r.ctrl.current().phase).toBe(TourPhase.FINISHED);
        assertJuryOutcomes(r.obs, (id: string) => r.statusOf(id));
        // the order scripts/smoke.sh greps for on the emulator
        const steps: string[][] = [['PACK_LOAD', 'pois=5'], ['ROUTE_PLAN', 'algo=heldkarp'], ['LOC_SOURCE', 'kind=demo']];
        for (const id of stopIds()) {
          steps.push(['POI_ENTER', `id=${id}`]);
          steps.push(['STORY_START', `poi=${id}`]);
        }
        steps.push(['STATE', 'to=finished']);
        steps.push(['STATE', 'ev=TEARDOWN why=finished']);
        expect(inOrder(r.obs, steps) >= 0).toBe(true);
        expect(r.obs.demoHoldSeen).toBe(true);                // "Demo assist" held the walker during a story
        expect(r.obs.lines('UNCAUGHT').length).toBe(0);
        expect(r.obs.lines('LOC_NOFIX').length).toBe(0);
        expect(r.sched.count()).toBe(0);                  // nothing left running after the finish
      });

    it('controller_skip_x2: Skip at every stop moves the walker to the new target; order and finish hold', async () => {
        const r: ControllerReplay = new ControllerReplay();
        await r.ctrl.setSource(FixSource.DEMO);
        await r.ctrl.plan(TOUR_ID, 0);
        r.ctrl.setDemoSpeed(2);                                  // the Home card's demo speed
        await r.ctrl.start();
        const jumps: string[] = r.walkSkipping();
        console.info(r.obs.summary('controller-skip-x2', r.ctrl.current().phase === TourPhase.FINISHED, r.seconds));
        console.info(`REPLAY_SKIP jumps=[${jumps.join(',')}]`);
        expect(r.ctrl.isRunning()).toBe(false);
        expect(r.ctrl.current().phase).toBe(TourPhase.FINISHED);
        assertPlannedOrder(r.obs);
        // after each Skip the walker stands at the stop the tour now targets (dot and tour agree)
        expect(jumps.join(',')).toBe('8:8,9:9,10:10,11:11');
        for (const id of stopIds().slice(1)) {
          expect(r.obs.count('LOC_SOURCE', `action=jump to=${id} `) >= 1).toBe(true);
        }
        // the skipped stories were skipped, nothing else: every stop was entered and its story started there
        for (const id of stopIds()) {
          expect(r.statusOf(id)).toBe(StopStatus.VISITED);
          expect(r.obs.count('STORY_START', `poi=${id}`) >= 1).toBe(true);
        }
        // jumping skips the walk, so no detour and no off-route
        expect(r.obs.lines('OFF_ROUTE').length).toBe(0);
        expect(r.obs.lines('UNCAUGHT').length).toBe(0);
      });
  });
}

replayTest();
