// Shared, platform-free code for the phone (entry) and watch (wearable) HAPs: contracts/ and core/.
// core/ must stay pure (no @kit imports): scripts/test.sh enforces it. Generated list, one line per file.
export * from './contracts/EngineTypes';
export * from './contracts/Model';
export * from './contracts/Ports';
export * from './contracts/Settings';
export * from './core/content/CityPack';
export * from './core/content/LangDetect';
export * from './core/content/NarrationSelector';
export * from './core/content/NarrationValidator';
export * from './core/content/PackParser';
export * from './core/content/Phrases';
export * from './core/geo/CourseEstimator';
export * from './core/geo/FixFilter';
export * from './core/geo/GeoMath';
export * from './core/geo/GridIndex';
export * from './core/geo/Projection';
export * from './core/haptics/CueMap';
export * from './core/hud/HudRows';
export * from './core/map/Camera';
export * from './core/map/ExploreMe';
export * from './core/map/PoiDots';
export * from './core/map/SheetDetents';
export * from './core/map/WalkDisplay';
export * from './core/notify/NotifyText';
export * from './core/onboarding/OnboardingRules';
export * from './core/remote/CanonicalJson';
export * from './core/remote/CourseRules';
export * from './core/remote/CoverRules';
export * from './core/remote/HomeRules';
export * from './core/remote/ServerApi';
export { isStreamCityFile, isClipFile, streamCourseFiles, streamClipFiles, streamCityFiles, courseSource, activeCandidates, streamNeedsPrepare, allPlacesAvailable, reusableForDownload, StreamRowActions, streamRowActions, ClipStep, STREAM_CLIP_BUDGET_MS, STREAM_PREFETCH, STREAM_OFFLINE_BACKOFF_MS, clipStep, StreamClip, prefetchAfter } from './core/remote/StreamRules';
// StreamRules.CourseSource (streamed/downloaded) clashes with CourseEstimator.CourseSource (walking direction).
export { CourseSource as StreamCourseSource } from './core/remote/StreamRules';
export * from './core/remote/VoiceChain';
export * from './core/route/Fallback';
export * from './core/route/Guidance';
export * from './core/route/HeldKarp';
export * from './core/route/LegTracker';
export { WALK_SPEED_MPS, SNAP_RADIUS_M, DEFAULT_DETOUR_FACTOR, CityPack, PlanInputs, buildCostInputs, plan } from './core/route/Planner';
export { haversineM as plannerHaversineM } from './core/route/Planner';
export * from './core/settings/SettingsRules';
export { DEMO_TICK_MS, DEMO_PROVIDER, DemoFix, DemoStop, DemoTrack, DemoTrackParse, parseDemoTrack, normalizeDemoSpeed, nextDemoSpeed, demoFixToFix, DemoTick, DemoWalkPlayer } from './core/sim/DemoWalkPlayer';
export * from './core/speech/ClipSelection';
export * from './core/speech/Sha256';
export * from './core/speech/VoicePolicy';
export * from './core/tour/AnnouncementQueue';
export * from './core/tour/LangSwitch';
export * from './core/tour/TourConfig';
export * from './core/tour/TourEngine';
export * from './core/tour/TourSummary';
export * from './core/tour/TriggerPolicy';
export * from './core/widget/CardModel';
export { FIX_TIMEOUT_MS, NO_FIRST_FIX_MS, TICK_MS, SNAPSHOT_MIN_INTERVAL_MS, OUT_OF_AREA_KM, ORIGIN_MAX_AGE_MS, ORIGIN_WAIT_MS, PLATFORM_START_TIMEOUT_MS, DemoControls, TourControllerDeps, TourOptions, kmOutsideBbox, predictNextUtteranceId, openStopIds, LOC_ERR_PERMISSION, LOC_ERR_SWITCH_OFF, locationErrorIssue, voiceIssueFor, enStatusOf, TourController } from './control/TourController';
// TourController.normalizeDemoSpeed (NaN => 4) differs from DemoWalkPlayer's (NaN => 1): re-exported renamed.
export { normalizeDemoSpeed as controllerNormalizeDemoSpeed } from './control/TourController';
export * from './app/LogEvents';
export * from './app/Clock';
export * from './debug/CorruptPackRepository';
