/*
 * Demo walk location source: SIMULATED (task A5, docs/ARCHITECTURE.md §5).
 * Replays the ACTIVE course's demo-walk.json (part of the downloaded, signed course pack; generated by
 * scripts/demo/make-demo-walk.mjs from the course's OSRM foot route; a course without one offers no Demo walk)
 * through the pure core/sim/DemoWalkPlayer, one fix per second (setInterval 1000 ms), speed x1/x2/x4/x8.
 * The emulator's GPS is a fixed point in Beijing and cannot be moved from the CLI (docs/RISKS.md §1 b4-b6), so this is
 * how the tour is shown on the emulator. Every fix has source DEMO and every LOC_FIX log line has src=demo.
 *   - Hold: at a stop the walker keeps standing while holdPredicate() is true (the controller wires it to
 *     "a story is playing"); isHolding() feeds PlatformStatus.demoHold ("Demo assist").
 *   - Timestamps: wall clock by default (consistent with the controller's Clock); setSimulatedTimestamps(true)
 *     stamps simulated track time instead (dwell/off-route timers then run at walking pace at any speed).
 * The track text comes from DemoTrackReader (ActivePackRepository.demoTrack: read and SHA-256-checked against the
 * pack manifest); a different course (key) reloads the track and restarts the walk.
 * Never throws: load and tick failures are logged and reported through onError.
 * iOS port: unchanged behaviour; only the timer handle type differs (React Native setInterval returns an opaque id).
 */
import { Fix, FixListener, FixSource, LocationErrorListener, LocationSource } from '@citytour/core';
import {
  DEMO_TICK_MS, DemoTick, DemoTrack, DemoWalkPlayer, normalizeDemoSpeed, parseDemoTrack
} from '@citytour/core';
import { AppConfig } from '../../app/AppConfig';
import { Log } from '../../app/Log';
import { LogEvents } from '@citytour/core';

/** The active course's demo track: `key` identifies the course version, `text` is demo-walk.json. */
export class DemoTrackText {
  key: string = '';
  text: string = '';
}

/** Reads the active course's demo track; undefined when the course has none. */
export type DemoTrackReader = () => Promise<DemoTrackText | undefined>;
/** onError codes of this source. */
export const DEMO_ERR_LOAD: number = 1;
export const DEMO_ERR_TICK: number = 2;
const LOC_FIX_LOG_EVERY_MS: number = 5000;

function fmt(v: number, digits: number): string {
  return Number.isFinite(v) ? v.toFixed(digits) : 'nan';
}

export class DemoWalkSource implements LocationSource {
  readonly kind: FixSource = FixSource.DEMO;
  private readonly reader: DemoTrackReader;
  private track: DemoTrack | undefined = undefined;
  private trackKey: string = '';
  private player: DemoWalkPlayer | undefined = undefined;
  private timer: ReturnType<typeof setInterval> | undefined = undefined;
  private running: boolean = false;
  private loading: boolean = false;
  private mult: number = normalizeDemoSpeed(AppConfig.DEMO_DEFAULT_SPEED);
  private holdPredicate: () => boolean = () => false;
  private holding: boolean = false;
  private ended: boolean = false;
  private simStamps: boolean = false;
  private lastTs: number = 0;
  private lastLogMs: number = 0;
  private lastFix: Fix | undefined = undefined;
  private onFix: FixListener | undefined = undefined;
  private onError: LocationErrorListener | undefined = undefined;
  private lastErr: string = '';

  constructor(reader: DemoTrackReader) {
    this.reader = reader;
  }

  isRunning(): boolean {
    return this.running;
  }

  /** Speed multiplier 1 | 2 | 4 | 8 (other values snap to the nearest). Takes effect on the next tick. */
  setSpeed(mult: number): void {
    const m = normalizeDemoSpeed(mult);
    if (m !== this.mult) {
      this.mult = m;
      Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true speed=x${m}`);
    }
  }

  speed(): number {
    return this.mult;
  }

  /** While it returns true, the walker stays at the current stop ("Demo assist: waiting while the story plays"). */
  setHoldPredicate(p: () => boolean): void {
    this.holdPredicate = p;
  }

  /** The last tick extended a stop hold: PlatformStatus.demoHold. */
  isHolding(): boolean {
    return this.holding;
  }

  setSimulatedTimestamps(on: boolean): void {
    this.simStamps = on;
  }

  /** Walk finished (the last sample was emitted and the hold, if any, released). */
  isFinished(): boolean {
    return this.ended;
  }

  progress(): number {
    return this.player !== undefined ? this.player.progress() : 0;
  }

  /** Stop number while standing at a stop, else 0. */
  currentStop(): number {
    return this.player !== undefined ? this.player.currentStop() : 0;
  }

  lastEmitted(): Fix | undefined {
    return this.lastFix;
  }

  lastError(): string {
    return this.lastErr;
  }

  /** TourControl.demoJumpToNext: skip to the next stop's arrival and emit that fix now. */
  jumpToNextStop(): number {
    if (this.player === undefined) {
      return 0;
    }
    const stop = this.player.jumpToNextStop();
    this.ended = false;
    Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true action=jump stop=${stop} i=${this.player.index()}`);
    if (this.running) {
      this.emit(this.player.current(), this.player.index(), false);
    }
    return stop;
  }

  /**
   * TourControl.skip / demoJumpToNext on the Demo walk: moves the walker to the start of the hold segment of the tour
   * stop `poiId` (track stop number from the track's stop list, else plannedIdx + 1) and emits that fix now.
   * Returns the stop number reached, 0 if the track has no such stop (the walker stays).
   */
  jumpToStop(poiId: string, plannedIdx: number): number {
    if (this.player === undefined) {
      return 0;
    }
    const byPoi = this.player.stopNumberOf(poiId);
    const n = byPoi > 0 ? byPoi : plannedIdx + 1;
    const stop = this.player.jumpToStop(n);
    Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true action=jumpToStop poi=${poiId} stop=${stop}` +
      ` by=${byPoi > 0 ? 'poi' : 'index'} i=${this.player.index()}`);
    if (stop > 0) {
      this.ended = false;
      if (this.running) {
        this.emit(this.player.current(), this.player.index(), false);
      }
    }
    return stop;
  }

  /** Starts or resumes the walk (a finished walk restarts from the beginning). */
  async start(onFix: FixListener, onError: LocationErrorListener): Promise<void> {
    this.onFix = onFix;
    this.onError = onError;
    if (this.running || this.loading) {
      return;
    }
    this.loading = true;
    try {
      const src = await this.reader();
      if (src === undefined) {
        this.reportError(DEMO_ERR_LOAD, 'no demo track in the active course');
        return;
      }
      if (this.track === undefined || src.key !== this.trackKey) {
        this.track = this.load(src);
        this.trackKey = this.track !== undefined ? src.key : '';
        this.player = undefined;   // another course: start its walk from the beginning
      }
      if (this.track === undefined) {
        return;   // load() reported the error
      }
      if (this.player === undefined || this.ended) {
        this.player = new DemoWalkPlayer(this.track);
        this.player.reset(Date.now());
        this.ended = false;
        this.lastTs = 0;
      }
      this.running = true;
      this.lastLogMs = 0;
      Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true state=start track=${this.track.id}` +
        ` fixes=${this.track.fixes.length} speed=x${this.mult} i=${this.player.index()}`);
      this.emit(this.player.current(), this.player.index(), false);
      this.timer = setInterval(() => {
        this.tick();
      }, DEMO_TICK_MS);
    } catch (e) {
      this.reportError(DEMO_ERR_LOAD, `start ${Log.errKv(e as Object)}`);
    } finally {
      this.loading = false;
    }
  }

  /** Pauses the walk at the current position (start() resumes). */
  stop(): void {
    if (this.timer !== undefined) {
      clearInterval(this.timer);
      this.timer = undefined;
    }
    if (this.running) {
      this.running = false;
      this.holding = false;
      Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true state=stop i=${this.player !== undefined ? this.player.index() : -1}`);
    }
  }

  /** Back to the first sample on the next start(). */
  rewind(): void {
    const wasRunning = this.running;
    this.stop();
    this.player = undefined;
    this.ended = false;
    if (wasRunning && this.onFix !== undefined && this.onError !== undefined) {
      this.start(this.onFix, this.onError);
    }
  }

  private tick(): void {
    if (!this.running || this.player === undefined) {
      return;
    }
    try {
      let hold = false;
      try {
        hold = this.holdPredicate();
      } catch (e) {
        hold = false;
      }
      const t: DemoTick = this.player.tick(this.mult * DEMO_TICK_MS, hold);
      if (t.holding !== this.holding) {
        Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true demoAssist=${t.holding ? 'hold' : 'release'}` +
          ` stop=${this.player.currentStop()}`);
      }
      this.holding = t.holding;
      this.emit(t.fix, t.index, true);
      if (t.ended) {
        this.ended = true;
        Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true state=end i=${t.index}`);
        this.stop();
      }
    } catch (e) {
      this.reportError(DEMO_ERR_TICK, `tick ${Log.errKv(e as Object)}`);
    }
  }

  private emit(f: Fix, index: number, rateLimit: boolean): void {
    let ts = this.simStamps ? f.timestampMs : Date.now();
    if (ts <= this.lastTs) {
      ts = this.lastTs + 1;   // FixFilter drops non-increasing timestamps
    }
    this.lastTs = ts;
    const fix: Fix = {
      lat: f.lat, lng: f.lng, accuracyM: f.accuracyM, speedMps: f.speedMps, courseDeg: f.courseDeg,
      courseAccuracyDeg: f.courseAccuracyDeg, timestampMs: ts, provider: f.provider, source: FixSource.DEMO
    };
    this.lastFix = fix;
    const now = Date.now();
    if (!rateLimit || now - this.lastLogMs >= LOC_FIX_LOG_EVERY_MS) {
      this.lastLogMs = now;
      // Demo coordinates at full precision (ARCHITECTURE §10).
      Log.i(LogEvents.LOC_FIX, `src=demo lat=${fmt(fix.lat, 6)} lng=${fmt(fix.lng, 6)} acc=${fmt(fix.accuracyM, 1)}` +
        ` spd=${fmt(fix.speedMps, 2)} crs=${fmt(fix.courseDeg, 0)} prov=${fix.provider} speed=x${this.mult}` +
        ` hold=${this.holding ? 1 : 0} stop=${this.player !== undefined ? this.player.currentStop() : 0}` +
        ` i=${index}/${this.track !== undefined ? this.track.fixes.length : 0}`);
    }
    if (this.onFix !== undefined) {
      try {
        this.onFix(fix);
      } catch (e) {
        Log.e(LogEvents.UNCAUGHT, `where=DemoWalkSource.onFix ${Log.errKv(e as Object)}`);
      }
    }
  }

  private load(src: DemoTrackText): DemoTrack | undefined {
    const t0 = Date.now();
    const r = parseDemoTrack(src.text);
    if (r.track === undefined) {
      this.reportError(DEMO_ERR_LOAD, `parse demo-walk.json course=${src.key} reason=${r.error}`);
      return undefined;
    }
    Log.i(LogEvents.LOC_SOURCE, `kind=demo simulated=true state=loaded course=${src.key} track=${r.track.id}` +
      ` fixes=${r.track.fixes.length} ms=${Date.now() - t0}`);
    return r.track;
  }

  private reportError(code: number, msg: string): void {
    this.lastErr = msg;
    Log.e(LogEvents.LOC_ERR, `src=demo code=${code} msg=${msg}`);
    if (this.onError !== undefined) {
      try {
        this.onError(code, msg);
      } catch (e) {
        Log.e(LogEvents.UNCAUGHT, `where=DemoWalkSource.onError ${Log.errKv(e as Object)}`);
      }
    }
  }
}
